---
abstract: 'Use Git::CPAN::Hook to commit each install in a Git repository'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-Dist-GitHook
requires:
  CPANPLUS: 0.9001
  Git::CPAN::Hook: 0.03
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/cpanplus-dist-githook
  repository: https://github.com/bingos/cpanplus-dist-githook
version: 0.02
